# fly.toml app configuration file generated for metacan on 2025-01-03T11:29:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'metacan'
primary_region = 'bos'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
